### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yb66** [scottgonzalez/jquery-ui-extensions#11]
or the total lack of it. In most projects that is a serious issue.

**Comment by scottgonzalez** [comment]
Most, but not all :-)

The extensions in this repo are pretty self-explanatory.

**Comment by yb66** [comment]
If they were, do you think I'd have opened an issue?

Here's a start:

How to install.
Do all the scripts need to be installed? (for example, for autocomplete)
Where do they need to be installed.
What difference do they make from the standard lib's?
Do they / will they run alongside the standard lib's ones?
Which versions of JQuery & UI do they work with.

Every project should have at the very least a readme with some basic install info, whether that's just a git clone command or to download or copy n paste... just _something_. Why? Because what's self explanatory to you isn't to everyone else, especially since you're the bloke who wrote the library.

If you want others to do this for you, make it clear that the wiki is for them to work with.

**Comment by scottgonzalez** [comment]
> How to install.

You don't "install" client-side JavaScript.

> Do all the scripts need to be installed? (for example, for autocomplete)

No, you use the extensions that you want. Look at the demos.

> Where do they need to be installed.

It doesn't matter where the scripts live, which is true for all JavaScript files.

> What difference do they make from the standard lib's?

The names of the plugins and the demos should make that fairly obvious. Feel free to send PRs to add descriptions to the demos.

> Do they / will they run alongside the standard lib's ones?

They're extensions. They require jQuery UI to be loaded.

> Which versions of JQuery & UI do they work with.

Presumably 1.8+, but to be honest, I don't do any testing beyond the day that I write the individual extensions.

---

This is currently a hodgepodge of extensions that I've built as demos for various reasons. At some point I will have time to actually write tests and documentation and add more extensions.

**Comment by yb66** [comment]
> You don't "install" client-side JavaScript.

Yes you do, by placing it somewhere.

> No, you use the extensions that you want. Look at the demos.

Ok.

> It doesn't matter where the scripts live, which is true for all JavaScript files.

Again, it needs to be placed somewhere, and then referred to. To a newbie, this is info they need.

> The names of the plugins and the demos should make that fairly obvious. Feel free to send PRs to add descriptions to the demos

I'm about to do that.

> They're extensions. They require jQuery UI to be loaded.

What I meant was, will they overwrite the current libs implementation of any of these things?

> Presumably 1.8+, but to be honest, I don't do any testing beyond the day that I write the individual extensions.

Thanks.
