### ISSUE TITLE
accentFolding works only with standard array of strings

### ISSUE THREAD

**Issue by andrasfuchs** [scottgonzalez/jquery-ui-extensions#13]
AccentFolding would be an excellent extension, but in many cases the source of the autocomplete is not just an array of strings, but array of objects.

E.g. in my project the source looks like this:

source: function (request, response) {
                    $.ajax({
                        url: "Home/SearchAutocomplete",
                        type: "POST",
                        dataType: "json",
                        data: {
                            featureClass: "P",
                            style: "full",
                            maxRows: 12,
                            name_startsWith: request.term
                        },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item.DisplayString,
                                    value: item.TreeNode.NodeType + ":" + item.TreeNode.UniqueName,
                                    icon: item.TreeNode.NodeType == "I" ? "./Content/svg/cat_bread_dark.svg" :
                                              (item.TreeNode.NodeType == "R" ? "./Content/svg/cat_pasta_dark.svg" : null)
                                }
                            }) // map
                            ); // response
                        } // success
                    }); // ajax
                },

So, it's an object with 3 properties: label, value and icon. In this case the extension will not know  - understandably - which property to use for accent folding and matching.

We should have a optional parameter to define the property to use.

**Comment by scottgonzalez** [comment]
It actually does know which one to fold, since it knows what's being search. What behavior are you seeing and what are you expecting to happen?

https://github.com/scottgonzalez/jquery-ui-extensions/blob/e34c9457619a13a01774f7954175320ac1e283c1/autocomplete/jquery.ui.autocomplete.accentFolding.js#L748

**Comment by andrasfuchs** [comment]
Hm.. interesting.

So, I have the following items with the following labels in the source: "tojás", "tojássárgája", "ananász" etc. etc.

When I start typing  "toj" both "tojás" and "tojássárgája" are displayed (correctly)
When I continue with an 'á' they are still displayed (also correctly)
But, when I start with "toj" and continue with "a", they both disappear. I expect to have them shown since 'á' is an accent of 'a'.

Is this expectation correct?

**Comment by scottgonzalez** [comment]
Sorry, just noticed your actual source. Accent folding is only for local data. If you're making remote request, then it's up to the server to return the correct data.

**Comment by scottgonzalez** [comment]
With that being said, the accept folding logic is exposed, so you can use it inside your success callback.

**Comment by andrasfuchs** [comment]
I see, I'll give a try in a minute. Thanks for the quick and proper reply!
