### ISSUE TITLE
Why not use the autoFocus options?

### ISSUE THREAD

**Issue by ZiadJ** [scottgonzalez/jquery-ui-extensions#17]
I don't understand what makes this plugin better than the already existing auto-focus option clearly documented here:

http://api.jqueryui.com/autocomplete/#option-autoFocus

**Comment by scottgonzalez** [comment]
The `autoFocus` option didn't exist when I wrote the `selectFirst` extension. I wrote both versions.

**Comment by ZiadJ** [comment]
Ok, but if you really care you'll want to inform your users about it on the landing page. I've lost a lot of my time modifying your extension to make it play well in my page lately only to find out a few days later that this is actually a built in!

**Comment by scottgonzalez** [comment]
This repo is pretty clearly not actively maintained right now. Why did you end up using an extension before looking at the options that ship with the official code?

**Comment by ZiadJ** [comment]
Because many people voted for it on stackoverflow. I just blindly followed the crowd. Was my bad but I'm not the only one(see previous issue). However it doesn't cost you anything to jot down a few words about it on your main page. If this extension is not actively maintained then why is it even here for us to download?

**Comment by scottgonzalez** [comment]
Here you go: 238fb0bf6dd5cfa50d41bfb064606bff21921568
