### ISSUE TITLE
Autocomplete (html option): autocomplete search takes into account html tags 

### ISSUE THREAD

**Issue by while0pass** [scottgonzalez/jquery-ui-extensions#2]
http://dev.nemikor.com/jquery-ui-extensions/autocomplete/html.html

Unfortunatelly, autocomplete search with html option takes into account html markup, though it should ignore it. For instance if I press "<", autocomplete gives me all the entries with html markup. The same is for typing tag names.

**Comment by scottgonzalez** [comment]
This was fixed a while ago, the demo just wasn't updated.

**Comment by while0pass** [comment]
ok, thank you.
