### ISSUE TITLE
making autocomplete match only from the beginning of the words

### ISSUE THREAD

**Issue by while0pass** [scottgonzalez/jquery-ui-extensions#3]
Is it possible to make autocomplete widget search in the way that it would match entries only from the beginning of the phrase or from the beginnning of any word in a phrase? For instance, if the list of entries is:
1. software engineering
2. computer networks
3. operating systems
4. databases
5. distributed systems
6. programming languages

and one types "s", autocomplete should show only 1), 3) and 5) ("software engineering", "operating systems" and "distributed systems"), but not all the 6 entries.

If it is not possible to get such autocomplete widget behaviour at the moment, I would like to propose it as an optional feature and open an issue.

**Comment by scottgonzalez** [comment]
You can implement any logic you want with a custom source option. See the accent folding code as an example.

**Comment by while0pass** [comment]
Thank you for a way out, Scott. Sorry for my little knowledge of jQuery UI.
