### ISSUE TITLE
error: item.eq is not a function

### ISSUE THREAD

**Issue by Gusep** [scottgonzalez/jquery-ui-extensions#4]
Hi,
great that you created this extension, though when I try to use it I got this JS error in jquery-ui file. (it's 2nd line of the activate function). I have no idea what might be causing this so if you could provide some advise..

Thanks

**Comment by scottgonzalez** [comment]
Please provide a demo showing the problem.

**Comment by Gusep** [comment]
ok, I took example from http://dev.nemikor.com/jquery-ui-extensions/autocomplete/selectFirst.html and used local js files with which I'm trying to make it work

so the demo is here: http://www.arskontakt.org/autocomplete/

**Comment by scottgonzalez** [comment]
Why are you using jQuery UI 1.8rc3? Please try using a newer version.
