### ISSUE TITLE
autocomplete.selectFirst needs an update for JUI 1.9

### ISSUE THREAD

**Issue by iksela** [scottgonzalez/jquery-ui-extensions#7]
In JQueryUI 1.9, the plugin autocomplete.selectFirst wont work.
In order to work with the updated ui-menu widget, line 19 should be:

``` javascript
menu.focus( $.Event({ type: "mouseenter" }), menu.element.children().first() );
```

(animate has been replaced by focus)

Hope this helps anyone trying the dev versions of JUI with this plugin.

**Comment by scottgonzalez** [comment]
You shouldn't be using selectFirst with 1.9; use the built-in autoFocus option instead.

**Comment by iksela** [comment]
Thanks!
