### ISSUE TITLE
The minLength property stops the show

### ISSUE THREAD

**Issue by stephaneeybert** [scottgonzalez/jquery-ui-extensions#8]
And Firebug has nothing to say either.

The drop down does not happen when the property minLength is being used.

With the following versions:

```
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/base/jquery-ui.css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.js"></script>
<script src="jquery.ui.autocomplete.html.js"></script>
```

**Comment by scottgonzalez** [comment]
That's not an adequate description. You don't even have sample code here.

**Comment by stephaneeybert** [comment]
Hi Scott,

I didn't know ifI should paste thewhole example code or not.

Here it is:

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>jQuery UI Autocomplete Extension - HTML Option</title>

```
<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/themes/base/jquery-ui.css">

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.17/jquery-ui.js"></script>
<script src="jquery.ui.autocomplete.html.js"></script>
<script>
  $(function() {
    $("#autocomplete").autocomplete({
      source: [
      {
        label: "aardvark", 
        value: "aardvark"
      },
      {
        label: "<b>apple</b>",
        value: "apple"
      },
      {
        label: "<i>atom</i>",
        value: "atom"
      }
      ],
      minLength: "2",
      html: true
    });
  });
</script>
```

  </head>
  <body>

```
<input id="autocomplete">
```

  </body>
</html>

**Comment by stephaneeybert** [comment]
I tried to attach it to the thread but maybe it's not possible.

I then removed the minLength property from my own application code, thinking it would now work fine with the html content, but it did not.

Here is the code I have in my application:

$().ready(function() {

  $("#$textFieldId").keyup(function() {
    if (!this.value) {
      $("#$hiddenFieldId").attr("value", '-1');
      $("#$textFieldId").attr("value", '');
    }
  });

  $("#$textFieldId").autocomplete({
    source: "$url",
    minLength: $minChar,
    html: true,
    select: function(event, ui) {
      if (ui.item) {
        $("#$hiddenFieldId").attr("value", ui.item.id);
      }
    }
  });

});

**Comment by scottgonzalez** [comment]
Why are you using a string for minLength?

**Comment by scottgonzalez** [comment]
Please provide a usable test case using jsFiddle or jsbin.

**Comment by stephaneeybert** [comment]
At first I was not, but then tried with a string see if it would help. Will provide a jsFiddle example.

**Comment by stephaneeybert** [comment]
Hi Scott

I saved a jsFiddle to notice my mistake.
Hard to believe.. or not, wrong path url to your plugin in my code. It works indeed. Sorry for that.

Steph
